//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHopDong
    {
        public int SoHD { get; set; }
        public string MAKO { get; set; }
        public System.DateTime NgayBDThue { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual KIOSK KIOSK { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
