//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGiamGiaTheoSL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietGiamGiaTheoSL()
        {
            this.ChiTietTangQuaTheoSLs = new HashSet<ChiTietTangQuaTheoSL>();
        }
    
        public int STT { get; set; }
        public int MaKM { get; set; }
        public int MaMH { get; set; }
        public int SLMuaToiThieu { get; set; }
        public decimal Giam { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DotKhuyenMai DotKhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTangQuaTheoSL> ChiTietTangQuaTheoSLs { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
