//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_TinhTrangKO
    {
        public int SCT { get; set; }
        public string MAKO { get; set; }
        public int MaTT { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.TimeSpan> GioBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual KIOSK KIOSK { get; set; }
        public virtual Loai_TinhTrang_KO Loai_TinhTrang_KO { get; set; }
    }
}
