//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThueKIOSKQC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietThueKIOSKQC()
        {
            this.ChiTietQCs = new HashSet<ChiTietQC>();
        }
    
        public int SoHD { get; set; }
        public string MAKO { get; set; }
        public System.DateTime NgayBDThue { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietQC> ChiTietQCs { get; set; }
        public virtual KIOSK KIOSK { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
