//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBA_MH
    {
        public int MaBA { get; set; }
        public int MaMH { get; set; }
        public bool TrangThaiMA { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual BuoiAn BuoiAn { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
