//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietQC
    {
        public int SoHD { get; set; }
        public string MAKO { get; set; }
        public int MaQC { get; set; }
        public System.DateTime NgayBDQC { get; set; }
        public System.DateTime NgayKTQC { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual QuangCao QuangCao { get; set; }
        public virtual ChiTietThueKIOSKQC ChiTietThueKIOSKQC { get; set; }
    }
}
