//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MaMH { get; set; }
        public int MaHD { get; set; }
        public int Soluong { get; set; }
        public decimal DonGiaBan { get; set; }
        public bool MangVe { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
