//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int MaHD { get; set; }
        public System.DateTime NgayLap { get; set; }
        public System.TimeSpan GioLap { get; set; }
        public decimal TongTriGia { get; set; }
        public decimal TongTriGiaDaKM { get; set; }
        public string MA_SSC { get; set; }
        public bool TrangThai_HoaDon { get; set; }
        public string MAKO { get; set; }
        public Nullable<int> MaHTTT { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual HinhThuc_ThanhToan HinhThuc_ThanhToan { get; set; }
        public virtual KIOSK KIOSK { get; set; }
    }
}
