//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIOSK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIOSK()
        {
            this.ChiTiet_TinhTrangKO = new HashSet<ChiTiet_TinhTrangKO>();
            this.ChiTietHopDongs = new HashSet<ChiTietHopDong>();
            this.ChiTietThueKIOSKQCs = new HashSet<ChiTietThueKIOSKQC>();
            this.HoaDons = new HashSet<HoaDon>();
            this.LanNaps = new HashSet<LanNap>();
        }
    
        public string MAKO { get; set; }
        public string MaToken { get; set; }
        public string TenKO { get; set; }
        public Nullable<System.DateTime> NgayXD { get; set; }
        public Nullable<System.DateTime> NgayVH { get; set; }
        public string DiaDiem { get; set; }
        public string NhietDo { get; set; }
        public bool TrangThaiKo { get; set; }
        public byte[] ImageBanner { get; set; }
        public string ConnectStr { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_TinhTrangKO> ChiTiet_TinhTrangKO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDong> ChiTietHopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThueKIOSKQC> ChiTietThueKIOSKQCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanNap> LanNaps { get; set; }
    }
}
