//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMTheoSLMH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KMTheoSLMH()
        {
            this.ChiTietTangQuaTheoSLMHs = new HashSet<ChiTietTangQuaTheoSLMH>();
            this.ChiTietTangQuaTheoTGHDs = new HashSet<ChiTietTangQuaTheoTGHD>();
        }
    
        public int STT { get; set; }
        public int SLMHToiThieu { get; set; }
        public decimal Giam { get; set; }
        public int MaKM { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTangQuaTheoSLMH> ChiTietTangQuaTheoSLMHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTangQuaTheoTGHD> ChiTietTangQuaTheoTGHDs { get; set; }
        public virtual DotKhuyenMai DotKhuyenMai { get; set; }
    }
}
