//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiMatHang1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiMatHang1()
        {
            this.DonVi_MatHang = new HashSet<DonVi_MatHang>();
        }
    
        public int MaLMH { get; set; }
        public string TenLMH { get; set; }
        public byte[] ImageLMH { get; set; }
        public Nullable<int> SoHD { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVi_MatHang> DonVi_MatHang { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
