//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.ChiTietGiamGiaTheoSLs = new HashSet<ChiTietGiamGiaTheoSL>();
            this.ChiTietBA_MH = new HashSet<ChiTietBA_MH>();
        }
    
        public int MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public int MaDV { get; set; }
        public bool TrangThai { get; set; }
        public byte[] ImageMH { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGiamGiaTheoSL> ChiTietGiamGiaTheoSLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBA_MH> ChiTietBA_MH { get; set; }
        public virtual DonVi_MatHang DonVi_MatHang { get; set; }
    }
}
