//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaTK { get; set; }
        public int MaCN { get; set; }
        public Nullable<System.DateTime> Ngay_CapNhat { get; set; }
        public Nullable<System.TimeSpan> Gio_CapNhat { get; set; }
        public bool TinhTrang { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ChucNang ChucNang { get; set; }
    }
}
