//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KIOSK
    {
        public string MAKO { get; set; }
        public string MaToken { get; set; }
        public string TenKO { get; set; }
        public Nullable<System.DateTime> NgayXD { get; set; }
        public Nullable<System.DateTime> NgayVH { get; set; }
        public string DiaDiem { get; set; }
        public string NhietDo { get; set; }
        public bool TrangThaiKo { get; set; }
        public byte[] ImageBanner { get; set; }
        public string ConnectStr { get; set; }
    }
}
