//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Admin_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MatHang
    {
        public int MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public int MaDV { get; set; }
        public string TenDV { get; set; }
        public bool TrangThai { get; set; }
        public byte[] ImageMH { get; set; }
    }
}
